name: Release

on:
  push:
    tags:
      - "*"

jobs:
  trigger-buildkite-pipeline:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.4.1"
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: "anza/agave-secondary"
          branch: "${{ github.ref_name }}"
          build_env_vars: '{"TRIGGERED_BUILDKITE_TAG": "${{ github.ref_name }}"}'
          commit: "HEAD"
          message: ":github: Triggered from a GitHub Action"

  draft-release:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-24.04
    steps:
      - name: Create Release
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ github.ref_name }}',
              name: 'Release ${{ github.ref_name }}',
              body: 'ðŸš§',
              draft: false,
              prerelease: true
            })

  version-bump:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.VERSION_BUMP_PAT }}

      - name: Setup
        run: |
          # install toml-cli
          cargo install toml-cli --locked

          # install xtask
          cargo install \
            --git https://github.com/anza-xyz/xtask \
            --rev 930e3baec27a17cb4491b5585515b33f94dbd039 \
            --bin xtask

          # git config
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Process
        id: process
        run: |
          xtask bump-version patch-or-pre-release

          new_version="$(toml get --raw Cargo.toml workspace.package.version)"

          git checkout -b version-bump-$new_version
          git commit -am "Bump version to $new_version"
          git push origin version-bump-$new_version

          echo "new_version=$new_version" | tee -a $GITHUB_OUTPUT

          base_ref="${{ github.event.base_ref }}"
          target_branch="${base_ref##*/}"
          echo "target_branch=$target_branch" | tee -a $GITHUB_OUTPUT

      - name: Create PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Bump version to ${{ steps.process.outputs.new_version }}',
              head: 'version-bump-${{ steps.process.outputs.new_version }}',
              base: '${{ steps.process.outputs.target_branch }}'
            })
